--菜单
insert into F_OPTINFO (OPTID, PREOPTID, OPTNAME, FORMCODE, OPTURL, MSGNO, MSGPRM, ISINTOOLBAR, IMGINDEX, TOPOPTID, OPTTYPE, ORDERIND, WFCODE, PAGETYPE)
values ('RCBGQBGL', 'YGJGGRBG', '签报管理', null, '...', null, null, 'Y', null, null, 'N', 3, null, 'F');


insert into F_OPTINFO (OPTID, PREOPTID, OPTNAME, FORMCODE, OPTURL, MSGNO, MSGPRM, ISINTOOLBAR, IMGINDEX, TOPOPTID, OPTTYPE, ORDERIND, WFCODE, PAGETYPE)
values ('QBDJ', 'RCBGQBGL', '签报登记', null, '/powerruntime/optApply!editDoOrRead.do?optId=OA_OPT&&itemId=QB-001&&isapplyuser=F&&flag=QB&&s_itemtype=QB&&show_type=F&&orgcode=1', null, null, 'Y', null, null, 'N', 4, null, 'F');

insert into F_OPTINFO (OPTID, PREOPTID, OPTNAME, FORMCODE, OPTURL, MSGNO, MSGPRM, ISINTOOLBAR, IMGINDEX, TOPOPTID, OPTTYPE, ORDERIND, WFCODE, PAGETYPE)
values ('QBDB', 'RCBGQBGL', '签报待办', null, '/dispatchdoc/vuserTaskListOA!list.do?s_itemtype=QB', null, null, 'Y', null, null, 'N', 5, null, 'F');

insert into F_OPTINFO (OPTID, PREOPTID, OPTNAME, FORMCODE, OPTURL, MSGNO, MSGPRM, ISINTOOLBAR, IMGINDEX, TOPOPTID, OPTTYPE, ORDERIND, WFCODE, PAGETYPE)
values ('QBCK', 'RCBGQBGL', '签报查看', null, '/oa/vOptBaseList!list.do?s_itemType=QB', null, null, 'Y', null, null, 'N', 6, null, 'F');

--签报权力信息
insert into B_POWER (ITEM_ID, ORG_ID, ITEM_NAME, ITEM_STA_NAME, ITEM_TYPE, TIME_LIMIT, IS_NETWORK, IS_FORMULA, PHONE, ADDRESS, LASTMODIFYTIME, FILE_NAME, AUDIT_SIGN, MONITOR_PHONE, ACCEPT_LINK, LEGAL_TIME_LIMIT, CHARGE, FORM_NAME, IN_FLOW_IMG_NAME, ISCHARGE, TRANSACT_DEPNAME, PROMISE_TYPE, ANTICIPATE_TYPE, QL_DEPID, QL_DEPSTATE, ENTRUST_NAME, QL_STATE, VERSION, BEGIN_TIME, END_TIME, PROCESS_DESC, ZF_ACCORDING, XW_ACCORDING, SRV_DIRECTORY, APPLY_FORM, QUESTION, REMARK, FREE_JUDGE, LEVY_UPON, CONDITION, IN_FLOW_INFO, IN_FLOW_IMG, CHARGE_BASIS, CHARGE_STANDARD, ACCEPT_CONDITION, PUNISHOBJECT, PUNISHBASISCONTENT, PUNISHBASIS, ISLAWSUIT, ISRECONSIDER, PUNISH_CLASS, DIS_STANDARD, DIS_DETAIL, ACCEPT_DEPNAME, COMPATIBLE_TYPE, ACCEPT_TIME_SCOPE, PROCESS_WORK_DESC, APPLY_FORM_DEMO, STATE_QUERY_URL, RESULT_QUERY_URL, REGULATORY_MEASURES, HAS_ITEM, SRV_DIRECTORY_STUFF, ITEM_CLASS, APPLY_MATERIAL, RISK, OUT_ITEM_ID, OPTITEMTYPE, OPTOPENSTYLE, ACTUALDEPENDENT)
values ('QB-001', 'JTT', '签报通用业务', null, 'QB', null, '1', null, null, null, to_date('16-12-2014 18:33:41', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null, null, null, null, null, null, null, null, null, 'JTT', '2', null, 'A', 0, to_date('16-12-2014 18:33:39', 'dd-mm-yyyy hh24:mi:ss'), null, '', '<CLOB>', '<CLOB>', '<CLOB>', '', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '', '<CLOB>', '<CLOB>', '<CLOB>', null, '<CLOB>', null, null, null, '<CLOB>', '<CLOB>', '<CLOB>', null, null, null, '<CLOB>', '', null, null, '<CLOB>', null, '', null, '<CLOB>', '<CLOB>', null, null, null, '<CLOB>');

insert into B_POWER (ITEM_ID, ORG_ID, ITEM_NAME, ITEM_STA_NAME, ITEM_TYPE, TIME_LIMIT, IS_NETWORK, IS_FORMULA, PHONE, ADDRESS, LASTMODIFYTIME, FILE_NAME, AUDIT_SIGN, MONITOR_PHONE, ACCEPT_LINK, LEGAL_TIME_LIMIT, CHARGE, FORM_NAME, IN_FLOW_IMG_NAME, ISCHARGE, TRANSACT_DEPNAME, PROMISE_TYPE, ANTICIPATE_TYPE, QL_DEPID, QL_DEPSTATE, ENTRUST_NAME, QL_STATE, VERSION, BEGIN_TIME, END_TIME, PROCESS_DESC, ZF_ACCORDING, XW_ACCORDING, SRV_DIRECTORY, APPLY_FORM, QUESTION, REMARK, FREE_JUDGE, LEVY_UPON, CONDITION, IN_FLOW_INFO, IN_FLOW_IMG, CHARGE_BASIS, CHARGE_STANDARD, ACCEPT_CONDITION, PUNISHOBJECT, PUNISHBASISCONTENT, PUNISHBASIS, ISLAWSUIT, ISRECONSIDER, PUNISH_CLASS, DIS_STANDARD, DIS_DETAIL, ACCEPT_DEPNAME, COMPATIBLE_TYPE, ACCEPT_TIME_SCOPE, PROCESS_WORK_DESC, APPLY_FORM_DEMO, STATE_QUERY_URL, RESULT_QUERY_URL, REGULATORY_MEASURES, HAS_ITEM, SRV_DIRECTORY_STUFF, ITEM_CLASS, APPLY_MATERIAL, RISK, OUT_ITEM_ID, OPTITEMTYPE, OPTOPENSTYLE, ACTUALDEPENDENT)
values ('QB-001', 'JTT', '签报通用业务', null, 'QB', null, '1', null, null, null, to_date('16-12-2014 18:33:41', 'dd-mm-yyyy hh24:mi:ss'), null, null, null, null, null, null, null, null, null, null, null, null, 'JTT', '2', null, 'A', 1, to_date('16-12-2014 18:33:39', 'dd-mm-yyyy hh24:mi:ss'), null, '', '<CLOB>', '<CLOB>', '<CLOB>', '', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '<CLOB>', '', '<CLOB>', '<CLOB>', '<CLOB>', null, '<CLOB>', null, null, null, '<CLOB>', '<CLOB>', '<CLOB>', null, null, null, '<CLOB>', '', null, null, '<CLOB>', null, '', null, '<CLOB>', '<CLOB>', null, null, null, '<CLOB>');

insert into C_POWER_OPT_INFO (ITEM_ID, WFCODE, RISKID, GROUP_ID, SETOPERATOR, SETIME, APPLY_ITEM_TYPE, RECORDID, VERSION, ISAPPLYUSER, OAMODULETYPE, ISGENERALMODULE, GENERALMODULECODE)
values ('QB-001', '000856', null, '343', '99999999', to_date('19-04-2016 09:05:47', 'dd-mm-yyyy hh24:mi:ss'), null, '1448867547934', null, 'F', 'C', 'T', 'qb_djr');

---材料分组

---签报模板
insert into TEMPLATE_FILE (TEMPLATEID, RECORDID, FILENAME, FILETYPE, FILESIZE, FILEDATE, FILEBODY, FILEPATH, USERNAME, DESCRIPT, ISUSED, TEMPTYPE, ORDERBY, CODECODE)
values (88, '1448867547934', null, '.doc', 10240, to_date('21-01-2016', 'dd-mm-yyyy'), '', '', 'Administrator', '签报正文', '1', 'SQWS', '20', null);

--修改视图 v_power_org_info 添加与 通用运行模块的关联
create or replace view v_power_org_info as
select t.item_id,t.unitcode, su.item_name,su.ITEM_TYPE,su.ORG_ID,su.QL_DepID,t.setime,t.setoperator,t.wfcode,wf.wfname,un.unitname,wf.OPTID,o.isapplyuser,
o.group_id,o.apply_item_type,o.recordid,doc.temptype as archiveType,doc.descript as docFileName,o.generalmodulecode
    from C_power_org_info t
    left join b_v_powerinusing su on t.item_id = su.item_id
    left join F_V_LASTVERTIONFLOW wf on wf.wfcode=t.wfcode
    left join f_unitinfo un on un.unitcode=t.unitcode
    left join C_POWER_OPT_INFO o on t.item_id = o.item_id
    left join TEMPLATE_FILE doc on doc.recordid=o.recordid
    where 1=1
    and su.ql_state = 'A';
    
    
----办件类型  字典项添加SQ
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('optTypeName', 'QB', null, '1', 'T', '签报', 'S', '签报', null, null);   


----办理页面提交按钮上文字显示
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('optComButton', 'QB', null, '7', 'T', '提交', 'S', null, null, null);


---添加流程流转字典项
insert into F_DATACATALOG (CATALOGCODE, CATALOGNAME, CATALOGSTYLE, CATALOGTYPE, CATALOGDESC, FIELDDESC, ISUPLOAD, DICTIONARYTYPE, CREATEDATE, LASTMODIFYDATE)
values ('qb_bgrcl', '签报办理人（签报）', 'U', 'L', null, null, '0', 'LCYW', null, null);

insert into F_DATACATALOG (CATALOGCODE, CATALOGNAME, CATALOGSTYLE, CATALOGTYPE, CATALOGDESC, FIELDDESC, ISUPLOAD, DICTIONARYTYPE, CREATEDATE, LASTMODIFYDATE)
values ('qb_ldqy', '分管主席批示（签报）', 'U', 'L', null, null, '0', 'LCYW', null, null);

insert into F_DATACATALOG (CATALOGCODE, CATALOGNAME, CATALOGSTYLE, CATALOGTYPE, CATALOGDESC, FIELDDESC, ISUPLOAD, DICTIONARYTYPE, CREATEDATE, LASTMODIFYDATE)
values ('qb_sh', '部门审核（签报）', 'U', 'L', null, null, '0', 'LCYW', null, null);


insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_bgrcl', 'bm', null, '1', 'T', '呈部处长审批', 'S', '呈部处长审批', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_bgrcl', 'cs', null, '2', 'T', '转部门会签', 'S', '转部门会签', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_sh', 'FG', null, '1', 'T', '呈分管主席批示', 'S', '呈分管主席批示', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_sh', 'JS', null, '5', 'T', '处理完成并结束', 'S', '处理完成并结束', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_sh', 'T', null, '3', 'T', '提交主办人办理', 'S', '提交主办人办理', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_sh', 'cs', null, '2', 'T', '转部门会签', 'S', '转部门会签', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_ldqy', 'F', null, '2', 'T', '呈主席批示', 'S', '呈主席批示', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_ldqy', 'T', null, '1', 'T', '提交部门处理', 'S', '提交部门处理', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('qb_sh', 'F', null, '6', 'T', '退回修改', 'S', '退回修改', null, null);

----添加流程属性配置
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_djr', '选择操作', 'qb_djr', '办理意见', 'F', null, null, 'T', '343', 'F', null, null, null, 'F', 'F', 'F', null, 'T', 'fwcsfzr', '选择核稿领导', 'D(U)', null, '1419318142402', 'T', null, null, '签报登记人（签报）', 'T', to_date('31-10-2016 10:01:10', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', null, null, null, null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'F', '主办人', 1, 'F', '{"type":""","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', null);


insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_sh', '选择操作', 'qb_sh', '办理意见', 'F', null, null, 'T', '343', 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'T', 'fgwldSH', '选择人员', 'D(''001801'')', null, '1448867547934', 'T', null, null, '部门审核（签报）', 'T', to_date('31-10-2016 14:45:26', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'T', 'zbcshq', '选择会签部门', 'D(ALL)', null, null, null, 'F', null, null, null, null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '处室核稿', 1, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', null);

insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_ng', '选择操作', 'qb_ng', '拟稿意见', 'F', null, null, 'T', '343', 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'F', 'zbcbr', '选择审核人员', 'D(U)', null, '1448867547934', 'T', null, null, '拟稿', 'F', to_date('25-05-2016 11:16:45', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', null, null, null, null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'F', '主办人', 1, 'F', '{"type":""","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', null);

insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_bmhq', '选择操作', null, '办理意见', 'F', null, null, 'T', '343', 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'F', null, null, null, null, '1448867547934', 'T', null, null, '部门会签（签报）', 'F', to_date('23-04-2016 10:12:51', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', null, null, null, null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '部门会签', 2, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', null);

insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_ldqy', '选择操作', 'qb_ldqy', '办理意见', 'F', null, null, 'F', '343', 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'T', 'zyldSP', '选择人员', 'D(''001801'')xz(ZT)', null, '1448867547934', 'T', null, null, '分管领导签阅（签报）', 'T', to_date('23-04-2016 10:13:56', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', null, null, null, null, null, null, 'F', null, '会签部门', null, 'F', null, null, null, null, 'F', 'F', 'T', '分管主席批示', 3, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', null);

insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_zyldqy', null, null, '办理意见', 'F', null, null, 'F', null, 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'F', null, null, null, null, '1448867547934', 'T', null, null, '主要领导批示（签报）', 'F', to_date('17-05-2016 08:39:48', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', null, null, null, null, 'T', '批示内容', 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '主席批示', 4, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} "}', 'F', null, null, 'F', null);

insert into c_general_module_param (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('qb_bgrcl', '选择操作', 'qb_bgrcl', '办理意见', 'F', null, null, 'T', '343', 'T', '修改正文', 'SQWS', '签报正文', 'F', 'F', 'F', null, 'F', 'qbbmhq', '选择人员', 'D(ALL)gw(FWcssh)', null, '1448867547934', 'T', null, null, '签报办理（签报）', 'T', to_date('08-05-2016 13:43:03', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'T', 'zbcshq', '选择会签部门', 'D(ALL)', null, null, null, 'F', 'BMHQ', '会签部门', null, null, null, null, 'F', null, '会签部门', null, 'F', null, null, null, null, 'F', 'F', 'T', '签报办理', 5, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent}<br>"}', 'F', null, null, 'F', null);