package com.centit.oa.po;
// default package
// Generated 2015-11-26 12:39:50 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VOaMeetApplyListId generated by hbm2java
 */
public class VOaMeetApplyList implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
    private String djid;
    private String applyNo;
    private String title;
    
    private Date applytime;
    private String meetingNo;
    private String depno;
    private String meetingName;
    private Date planBegTime;
    private Date planEndTime;
    private Date doBegTime;
    private Date doEndTime;
    private String telephone;
    private Long meetingPersionsNum;
    private String state;
    private String usercode;
    private String unitcode;
    private Date opertime;
    private String optid;
    private Long flowinstid;
    private String flowcode;
    private String transaffairname;
    private String bizstate;
    private String powerid;
    private String powername;
    private String solvestatus;
    private Date solvetime;
    private String solvenote;
    private String acceptarchiveno;
    private String biztype;

    public VOaMeetApplyList() {
    }

    public String getDjid() {
        return this.djid;
    }

    public void setDjid(String djid) {
        this.djid = djid;
    }

    public String getApplyNo() {
        return this.applyNo;
    }

    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getApplytime() {
        return this.applytime;
    }

    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    public String getMeetingNo() {
        return this.meetingNo;
    }

    public void setMeetingNo(String meetingNo) {
        this.meetingNo = meetingNo;
    }

    public Date getPlanBegTime() {
        return this.planBegTime;
    }

    public void setPlanBegTime(Date planBegTime) {
        this.planBegTime = planBegTime;
    }

    public Date getPlanEndTime() {
        return this.planEndTime;
    }

    public void setPlanEndTime(Date planEndTime) {
        this.planEndTime = planEndTime;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Long getMeetingPersionsNum() {
        return this.meetingPersionsNum;
    }

    public void setMeetingPersionsNum(Long meetingPersionsNum) {
        this.meetingPersionsNum = meetingPersionsNum;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getUsercode() {
        return this.usercode;
    }

    public void setUsercode(String usercode) {
        this.usercode = usercode;
    }

    public String getUnitcode() {
        return this.unitcode;
    }

    public void setUnitcode(String unitcode) {
        this.unitcode = unitcode;
    }

    public Date getOpertime() {
        return this.opertime;
    }

    public void setOpertime(Date opertime) {
        this.opertime = opertime;
    }

    public String getOptid() {
        return this.optid;
    }

    public void setOptid(String optid) {
        this.optid = optid;
    }

    public Long getFlowinstid() {
        return this.flowinstid;
    }

    public void setFlowinstid(Long flowinstid) {
        this.flowinstid = flowinstid;
    }

    public String getFlowcode() {
        return this.flowcode;
    }

    public void setFlowcode(String flowcode) {
        this.flowcode = flowcode;
    }

    public String getTransaffairname() {
        return this.transaffairname;
    }

    public void setTransaffairname(String transaffairname) {
        this.transaffairname = transaffairname;
    }

    public String getBizstate() {
        return this.bizstate;
    }

    public void setBizstate(String bizstate) {
        this.bizstate = bizstate;
    }

    public String getPowerid() {
        return this.powerid;
    }

    public void setPowerid(String powerid) {
        this.powerid = powerid;
    }

    public String getPowername() {
        return this.powername;
    }

    public void setPowername(String powername) {
        this.powername = powername;
    }

    public String getSolvestatus() {
        return this.solvestatus;
    }

    public void setSolvestatus(String solvestatus) {
        this.solvestatus = solvestatus;
    }

    public Date getSolvetime() {
        return this.solvetime;
    }

    public void setSolvetime(Date solvetime) {
        this.solvetime = solvetime;
    }

    public String getSolvenote() {
        return this.solvenote;
    }

    public void setSolvenote(String solvenote) {
        this.solvenote = solvenote;
    }

    public String getAcceptarchiveno() {
        return this.acceptarchiveno;
    }

    public void setAcceptarchiveno(String acceptarchiveno) {
        this.acceptarchiveno = acceptarchiveno;
    }

    public String getBiztype() {
        return this.biztype;
    }

    public void setBiztype(String biztype) {
        this.biztype = biztype;
    }

    public Date getDoBegTime() {
        return doBegTime;
    }

    public void setDoBegTime(Date doBegTime) {
        this.doBegTime = doBegTime;
    }

    public Date getDoEndTime() {
        return doEndTime;
    }

    public void setDoEndTime(Date doEndTime) {
        this.doEndTime = doEndTime;
    }

    public String getDepno() {
        return depno;
    }

    public void setDepno(String depno) {
        this.depno = depno;
    }

    public String getMeetingName() {
        return meetingName;
    }

    public void setMeetingName(String meetingName) {
        this.meetingName = meetingName;
    }
    
}
