-----SW_LDYJSY
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'B', null, '6', 'T', '完成阅办', 'S', '完成阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'T', null, '4', 'T', '转部处长阅办', 'S', '转部处长阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'F', null, '2', 'T', '呈主席阅示', 'S', '呈主席阅示', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'TF', null, '1', 'T', '呈主席及部门阅', 'S', '呈主席及部门阅', null, null);

---sw_tbpf

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'T', null, '3', 'T', '转部门阅办', 'S', '转部门阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'TFG', null, '1', 'T', '呈主席及部门阅', 'S', '呈主席及部门阅', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'B', null, '4', 'T', '完成阅办', 'S', '完成阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'FG', null, '2', 'T', '呈主席阅示', 'S', '呈主席阅示', null, null);


--sw_tbpf
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('sw_tbpf', '选择操作', 'sw_tbpf', '办理意见', 'F', null, null, 'F', '251', 'F', '修改正文', 'zw', null, 'F', 'F', 'F', null, 'T', 'fgwldSH', '选择人员', 'D(''001801'')', null, null, 'T', null, null, '厅办主任批分（收文）', 'T', to_date('17-08-2016 10:18:29', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'T', 'BMSW', '选择接收部门', 'D(all)', null, null, null, 'F', 'zyldpy', '选择人员', 'D(''001801'')xz(ZT)', null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '拟办意见', 1, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br>"} ', 'F', null, null, 'T', null);

--SW_LDYJSY
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('SW_LDYJSY', '选择操作', 'SW_LDYJSY', '办理意见', 'F', null, null, 'F', null, 'F', null, null, null, 'F', 'F', 'F', null, 'T', 'fgwldSH', '选择人员', 'D(''001801'')', null, null, 'T', null, null, '领导意见汇总（收文）', 'T', to_date('17-08-2016 10:18:59', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', 'BMSW', '选择阅办文部门', 'D(all)', null, null, null, 'T', 'zyldpy', '选择人员', 'D(''001801'')xz(ZT)', null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'F', '文书分发', 2, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'T', null);


--sw_fgldpy
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('sw_fgldpy', null, null, '办理意见', 'F', null, null, 'F', '251', 'F', '修改正文', 'zw', null, 'F', 'F', 'F', null, 'F', null, '选择人员', 'D(''001801'')', null, null, 'T', null, null, '分管主席批阅（收文）', 'F', to_date('17-08-2016 15:24:43', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', 'BMSW', '选择收文部门', 'D(all)', 'zbcsfb', null, null, 'F', 'BMHQ', '选择人员', 'D(all)', null, null, null, 'F', null, '选择接收部门', 'D(all)', 'F', null, null, null, null, 'F', 'F', 'T', '主席批阅', 3, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'F', 'F');

---sw_bl  （部门办理不需要人员内部转办）
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('sw_bl', '选择操作', 'sw_bl', '办理意见', 'F', null, null, 'T', '333', 'F', null, null, null, 'F', 'F', 'F', null, 'F', 'jbr', '选择人员', 'D(U)', null, null, 'T', null, null, '业务处室收文办理（收文）', 'F', to_date('17-08-2016 15:43:42', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, null, null, null, null, null, 'F', 'zbcbr', '选择人员', 'D(U)', null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '办理结果', 5, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'T', null);



/*对应阅办文版本号107
 * 
 * 
-----备份通用运行模块
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('sw_tbpf', '选择操作', 'sw_tbpf', '办理意见', 'F', null, null, 'F', '251', 'F', '修改正文', 'zw', null, 'F', 'F', 'F', null, 'T', 'fgwldSH', '选择人员', 'D(''001801'')xz(FT)', null, null, 'T', null, null, '厅办主任批分（收文）', 'T', to_date('14-06-2016 12:00:00', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'T', 'BMSW', '选择接收部门', 'D(all)', null, null, null, 'T', 'zyldpy', '选择人员', 'D(''001801'')xz(ZT)', null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'T', '拟办意见', 1, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br>"} ', 'F', null, null, 'T', null);

---备份通用运行模块 SW_LDYJSY
insert into C_GENERAL_MODULE_PARAM (MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ, HASDX, TIPS, CANSENDMESSAGE, BTIDEA)
values ('SW_LDYJSY', '选择操作', 'SW_LDYJSY', '办理意见', 'F', null, null, 'F', null, 'F', null, null, null, 'F', 'F', 'F', null, 'T', 'fgwldSH', '选择人员', 'D(''001801'')xz(FT)', null, null, 'T', null, null, '领导意见汇总（收文）', 'T', to_date('14-06-2016 00:00:01', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'T', 'BMSW', '选择阅办文部门', 'D(all)', null, null, null, 'T', 'zyldpy', '选择人员', 'D(''001801'')xz(ZT)', null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'F', '文书分发', 2, 'F', '{"type":"","DATE_PATTERN":"yyyy/MM/dd HH:mm","dataModule":"{username} {transdate} : {transcontent} </br></br>"} ', 'F', null, null, 'T', null);

---备份sw_tbpf
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'T', null, '3', 'T', '转部门阅办', 'S', '转部门阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'F', null, '1', 'T', '呈主席阅示', 'S', '呈主席阅示', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'B', null, '4', 'T', '完成阅办', 'S', '完成阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('sw_tbpf', 'FG', null, '2', 'T', '呈分管主席阅示', 'S', '呈分管主席阅示', null, null);

-----备份SW_LDYJSY
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'B', null, '6', 'T', '完成阅办', 'S', '完成阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'T', null, '4', 'T', '转部处长阅办', 'S', '转部处长阅办', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'F', null, '2', 'T', '呈分管主席阅示', 'S', '呈分管主席阅示', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('SW_LDYJSY', 'LD', null, '1', 'T', '呈主席阅示', 'S', '呈主席阅示', null, null);
*/
