
insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('FW_CSSH', 'HG', null, '4', 'T', '提交核稿', 'S', '提交核稿', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('FW_LDHQ', 'F', null, '3', 'T', '退回办公室负责人', 'S', '退回办公室负责人', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('FW_LDHQ', 'ZWH', null, '4', 'T', '置文号', 'S', '置文号', null, null);

insert into F_DATADICTIONARY (CATALOGCODE, DATACODE, EXTRACODE, EXTRACODE2, DATATAG, DATAVALUE, DATASTYLE, DATADESC, LASTMODIFYDATE, CREATEDATE)
values ('FW_mshg', 'F', null, '1', 'T', '退回部门审核', 'S', '退回部门审核', null, null);


insert into C_GENERAL_MODULE_PARAM ( MODULECODE, IDEALABEL, IDEACATALOG, IDEACONTENT, HASATTENTION, ATTENTIONLABEL, ATTENTIONFILTER, HASSTUFF, STUFF_GROUP_ID, HASDOCUMENT, DOCUMENTLABEL, DOCUMENTTYPE, DOCUMENTTEMPLATENAMES, CANDEFER, CANROLLBACK, CANCLOSE, RISKID, ASSIGNTEAMROLE, TEAMROLECODE, TEAMROLENAME, TEAMROLEFILTER, MUSTCREATEDOC, DOCUMENTTEMPLATEIDS, ISINUSE, SUBMITOPTURI, SAVEOPTURI, NODENAME, HASIDEA, LASTUPDATETIME, DOCREADONLY, HASPREIDEA, HASORGROLE, XB_ORGROLECODE, XB_ORGROLENAME, XB_ORGROLEFILTER, ZB_ORGROLECODE, ZB_ORGROLENAME, ZB_ORGROLEFILTER, ASSIGNENGINEROLE, ENGINEROLECODE, ENGINEROLENAME, ENGINEROLEFILTER, ISTEAMROLECHECK, ISQUICKCONTENT, QUICKCONTENTRESULT, HASZBUSER, ZB_USERROLECODE, ZB_USERLABEL, ZB_USERFILTER, HASXBUSER, XB_USERROLECODE, XB_USERLABEL, XB_USERFILTER, BOOKMARKTYPE, HASSQ, HASFW, ISSHOWINNODE, NODELABEL, NODEORDER, HASQB, IDEAMODULE, HASJZ)
values ( 'FW_CSSH_exp3', '审核结果', null, '办理意见', 'F', null, null, 'F', null, 'T', '拟文稿纸', 'zw', null, 'F', 'T', 'F', null, 'T', 'fwcsfzr', '选择核稿人员', 'D(U||U-1)gw(FWcssh)', null, null, 'T', null, null, '处室负责人审核(会签信息)（发文）', 'F', to_date('22-04-2016 11:29:46', 'dd-mm-yyyy hh24:mi:ss'), 'F', 'F', 'F', null, '选择会签部门', 'D(all)', null, null, null, 'F', null, null, null, null, null, null, 'F', null, null, null, 'F', null, null, null, null, 'F', 'F', 'F', null, null, null, null, 'F');

